site_name: "디지털 심화 과정"

nav:
  - 1.강의 개요 / 학습 소개: 
      - 3d기본 :         
        - mesh&nurb: "1년간_학습/3d_basic/mesh_nurb.md"
      - 3d modeling :         
        - AutoCAD : "1년간_학습/3d_modeling_tools/AutoCAD.md"
        - Sketchup : "1년간_학습/3d_modeling_tools/Sketchup.md"
        - Revit : "1년간_학습/3d_modeling_tools/Revit.md"
        - Rhino3d : "1년간_학습/3d_modeling_tools/Rhino3d.md"
        
  - 2.SketchUp기초 (2D 디자인) :       
      - 기본 : "sketchup2/basic.md"
      - 인터페이스 : "sketchup2/interface.md"
      - 과제 : "sketchup2/assessment.md"
  - 3.SketchUp시작 (3D 모델링): 
      - 모델링 : "sketchup3/modeling.md"
  - 4.SketchUp과 플러그인: 
      - 플러그인 : "sketchup4/ruby.md"
  - 5.SketchUp과 웨어하우스 : 
      - 웨어하우스 : "sketchup5/warehouse.md"
      - 플러그인(2): "sketchup5/plugin2.md"
  - 6.SketchUp 텍스처/조명효과:
      - 택스쳐 및 조명 : "sketchup6/lighttexture.md"
  - 7.Enscape SketchUp (1):
      - Enscape : "sketchup7/enscape.md"
  - 8.Enscape SketchUp (2):
      - 엔스케이프_고급 : "enscape8/gen3d.md"
  - 9.중간 프로젝트 QnA :
      - 프로젝트 내용 : "midtest9/gen3d.md"
  - 10.중간 프로젝트 발표 :
      - 프로젝트 내용 : "midtest10/gen3d.md"  
  - 11.오토캐드 입문 (1) :
      - 프로젝트 내용 : "AutoCAD11/gen3d.md"    
  - 12.오토캐드 입문 (2) :
      - 프로젝트 내용 : "AutoCAD12/gen3d.md"          
  - 13.오토캐드 실무 (3) :
      - 프로젝트 내용 : "AutoCAD13/gen3d.md"     
  - 14.오토캐드 출력/공유(4) :
      - 프로젝트 내용 : "AutoCAD14/gen3d.md"   
  - 15.최종 프로젝트  :
      - 프로젝트 내용 : "AutoCAD15/gen3d.md"  


theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "favicon.ico"
  palette:
    primary: "orange"  # Escaping hex code
    accent: "dark orange"
extra_css:
  - css/custom.css
markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
